name: CI

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: ls -al

      - name: mkdir
        run: mkdir test

      - name: pwd
        run: pwd

      # - name: test2
      #   run: sh /home/ubuntu/canvasary/deploy.sh
