name: CI

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: ls -al
      - run: pwd

      - name: test
        run: sh /home/ubuntu/canvasary/deploy.sh
