name: CI

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: ls -al
      - uses: actions/checkout@v4
      - run: ls -al
      - run: cat .github/workflows/test.yml

      - name: mkdir
        run: mkdir test

      - name: pwd
        run: pwd

      # - name: test2
      #   run: sh /home/ubuntu/canvasary/deploy.sh
